version: '3.8'
services:
  bridge-app:
    container_name: rs485-bridge
    user: root
    build:
      context: .
      dockerfile: ./src/BridgeApp/Dockerfile
    restart: always
    network_mode: "host"
    privileged: true
    devices:
      - "/dev/fb1:/dev/fb1"
    volumes:
      - /dev:/dev # 시리얼 포트 접근용
    environment:
      - BRIDGE_NAME=${BRIDGE_NAME}
      - MAINFRAME_URL=${MAINFRAME_URL}
      - AES_KEY=${ENCRYPTION_KEY}
      - DOTNET_ENVIRONMENT=Production
